name: icicles_animation_template_dart
description: An icicles animation generator template.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  icicles_animation_dart:
    git:
      url: https://github.com/led-icicles/icicles_animation_dart.git
      ref: v0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
